In [159]:
import komm
import numpy as np      

In [160]:
code23 = komm.ConvolutionalCode([
                                [0b11, 0b10, 0b11],
                                [0b10, 0b01, 0b01]
                                ])      

(n, k, mu) = (code23.num_output_bits, code23.num_input_bits, code23.memory_order)

print((n, k, mu))

encoder = komm.ConvolutionalStreamEncoder(code23, state=0)

print("vetor com código de correção (passo1): ", encoder([0,1,1,1,1,0]))
print("vetor com código de correção (pass02): ", encoder([0,1,1,1,1,0]))

(3, 2, np.int64(1))
vetor com código de correção (passo1):  [0 1 1 0 1 0 1 1 0]
vetor com código de correção (pass02):  [1 0 0 0 1 0 1 1 0]


In [161]:
code12 = komm.ConvolutionalCode([[0b111, 0b101]])

(n, k, mu) = (code12.num_output_bits, code12.num_input_bits, code12.memory_order)

print((n, k, mu))

encoder = komm.ConvolutionalStreamEncoder(code12, state=0)

print("vetor com código de correção (passo1): ", encoder([1,0,1,1,0]))
print("vetor com código de correção (passo2): ", encoder([1,0,1,1,0]))


(2, 1, np.int64(2))
vetor com código de correção (passo1):  [1 1 1 0 0 0 0 1 0 1]
vetor com código de correção (passo2):  [0 0 1 0 0 0 0 1 0 1]


In [162]:
fsm = code23.finite_state_machine
print(fsm)

FiniteStateMachine(next_states=[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]], outputs=[[0, 5, 6, 3], [7, 2, 1, 4], [1, 4, 7, 2], [6, 3, 0, 5]])


In [163]:
block_code_trunc = komm.TerminatedConvolutionalCode(code12, num_blocks=5, mode="direct-truncation")

print("Comprimento código truncado: ", block_code_trunc.length)
print("Dimensão código truncado: ", block_code_trunc.dimension)
print("Distância minima código truncado: ", block_code_trunc.minimum_distance)
print("Matrix do código truncado: ", block_code_trunc.generator_matrix)

encoder_trunc = block_code_trunc.enc_mapping([1,0,1,1,0])

print("vetor com código de correção truncado: ", encoder_trunc)

Comprimento código truncado:  10
Dimensão código truncado:  5
Distância minima código truncado:  2
Matrix do código truncado:  [[1 1 1 0 1 1 0 0 0 0]
 [0 0 1 1 1 0 1 1 0 0]
 [0 0 0 0 1 1 1 0 1 1]
 [0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 1 1]]
vetor com código de correção truncado:  [1 1 1 0 0 0 0 1 0 1]


In [164]:
block_code_zero = komm.TerminatedConvolutionalCode(code12, num_blocks=5, mode="zero-termination")

print("Comprimento código truncado: ", block_code_zero.length)
print("Dimensão código truncado: ", block_code_zero.dimension)
print("Distância minima código truncado: ", block_code_zero.minimum_distance)
print("Matrix do código truncado: ", block_code_zero.generator_matrix)

encoder_trunc = block_code_zero.enc_mapping([1,0,1,1,0])

print("vetor com código de correção truncado: ", encoder_trunc)



Comprimento código truncado:  14
Dimensão código truncado:  5
Distância minima código truncado:  5
Matrix do código truncado:  [[1 1 1 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 1 1]]
vetor com código de correção truncado:  [1 1 1 0 0 0 0 1 0 1 1 1 0 0]


In [165]:
block_code_tail = komm.TerminatedConvolutionalCode(code12, num_blocks=5, mode="tail-biting")

print("Comprimento código tail-biting: ", block_code_tail.length)
print("Dimensão código tail-biting: ", block_code_tail.dimension)
print("Distância minima código tail-biting: ", block_code_tail.minimum_distance)
print("Matrix do código tail-biting: ", block_code_tail.generator_matrix)

encoder_tail = block_code_tail.enc_mapping([1,0,1,1,0])

print("vetor com código de correção tail-biting: ", encoder_tail)

Comprimento código tail-biting:  10
Dimensão código tail-biting:  5
Distância minima código tail-biting:  3
Matrix do código tail-biting:  [[1 1 1 0 1 1 0 0 0 0]
 [0 0 1 1 1 0 1 1 0 0]
 [0 0 0 0 1 1 1 0 1 1]
 [1 1 0 0 0 0 1 1 1 0]
 [1 0 1 1 0 0 0 0 1 1]]
vetor com código de correção tail-biting:  [0 0 1 0 0 0 0 1 0 1]


In [166]:
h = 100
block_code12_trunc = komm.TerminatedConvolutionalCode(code12, num_blocks=h, mode="zero-termination")

encoder = komm.BlockEncoder(block_code12_trunc)

u = np.random.randint(0, 2, h)

v = encoder(u)

print(v)

[0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0
 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0 1 1 0 1 0 1 0 0 0 1
 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 0
 0 0 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0
 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0
 1 1 0 1 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0]


In [ ]:
channel = komm.BinarySymmetricChannel(0.1)

b = channel(v)

print(b)

print("Quantidade de erros (entre transmissão e recepção): ", np.sum(v != b))

[0 0 0 0 1 0 1 1 0 1 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0
 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1
 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 1 1 0 1 0
 0 0 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1 1 0 0 1
 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 0 0 0 0
 1 0 0 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0]
Quantidade de erros:  22


In [168]:
decoder = komm.BlockDecoder(block_code12_trunc, method="viterbi_hard")

u_hat = decoder(b)

print(u_hat)

print("BER: ", np.sum(u != u_hat))

[0 0 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 1 1 0 1 1
 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 1 0
 0 1 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 0 1 1 1 0 0 0 1 0]
BER:  14
