In [1]:
# Import das bibliotecas do Python
import sys
import komm
import numpy as np
import pandas as pd
import itertools as it
from itertools import product
from fractions import Fraction 

# Cria um objeto do código de Hamming (7,4)
hamm74 = komm.HammingCode(3)
(n, k) = (hamm74.length, hamm74.dimension)

# Imprime o código de Hamming (7,4)
print("Código de Hamming (7,4):")
print(n, k)

# Cria e Imprime a matriz geradora G (7,4)
G = hamm74.generator_matrix
print("Matriz geradora G (7,4):")
print(G)

Código de Hamming (7,4):
7 4
Matriz geradora G (7,4):
[[1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 1 1]]


In [2]:
# Calcula o bit de paridade para cada linha e adiciona à matriz

# Calcula a paridade (soma módulo 2 de cada linha)
parity_column = np.sum(G, axis=1)


# Adiciona a coluna de paridade
G_extended = np.hstack((G, parity_column.reshape(-1, 1)))  

# Imprime a matriz geradora estendida (8,4)
print("\nMatriz geradora estendida G (8,4):")
print(G_extended)


Matriz geradora estendida G (8,4):
[[1 0 0 0 1 1 0 3]
 [0 1 0 0 1 0 1 3]
 [0 0 1 0 0 1 1 3]
 [0 0 0 1 1 1 1 4]]


In [3]:
# Define a função para mapear a mensagem para uma palavra código de 8 bits
def encode_message(m, G_extended):
    # Converte a mensagem em um array numpy, caso ainda não seja
    m = np.array(m)
    # Multiplica a mensagem pela matriz geradora estendida no campo GF(2)
    codeword = np.dot(m, G_extended) % 2  # Calcula a palavra código em aritmética módulo 2
    return codeword

# Exemplo de uso
message = [1, 0, 1, 1]  # Mensagem de 4 bits
codeword = encode_message(message, G_extended)

print("Mensagem de entrada (4 bits):", message)
print("Palavra código gerada (8 bits):", codeword)

# Altera o comprimento de n para 8
n = n + 1

# calcula o número de bits da mensagem 
m_lenght = n - k

Mensagem de entrada (4 bits): [1, 0, 1, 1]
Palavra código gerada (8 bits): [1 0 1 1 0 1 0 0]


In [4]:
# Gera todas as mensagens de 4 bits possíveis
all_messages = list(product([0, 1], repeat=4))  # Gera combinações de 4 bits

# Exibe cada mensagem e sua palavra código correspondente
print("Mensagem (4 bits) -> Palavra código (8 bits)")
for m in all_messages:
    codeword = encode_message(m, G_extended)
    print(f"{m} -> {codeword}")

Mensagem (4 bits) -> Palavra código (8 bits)
(0, 0, 0, 0) -> [0 0 0 0 0 0 0 0]
(0, 0, 0, 1) -> [0 0 0 1 1 1 1 0]
(0, 0, 1, 0) -> [0 0 1 0 0 1 1 1]
(0, 0, 1, 1) -> [0 0 1 1 1 0 0 1]
(0, 1, 0, 0) -> [0 1 0 0 1 0 1 1]
(0, 1, 0, 1) -> [0 1 0 1 0 1 0 1]
(0, 1, 1, 0) -> [0 1 1 0 1 1 0 0]
(0, 1, 1, 1) -> [0 1 1 1 0 0 1 0]
(1, 0, 0, 0) -> [1 0 0 0 1 1 0 1]
(1, 0, 0, 1) -> [1 0 0 1 0 0 1 1]
(1, 0, 1, 0) -> [1 0 1 0 1 0 1 0]
(1, 0, 1, 1) -> [1 0 1 1 0 1 0 0]
(1, 1, 0, 0) -> [1 1 0 0 0 1 1 0]
(1, 1, 0, 1) -> [1 1 0 1 1 0 0 0]
(1, 1, 1, 0) -> [1 1 1 0 0 0 0 1]
(1, 1, 1, 1) -> [1 1 1 1 1 1 1 1]


In [5]:
# Calcula o peso de Hamming de uma palavra código

# Vetores para armazenar as palavras-código e seus pesos
codewords = []
weights = []

# Calcula o peso de Hamming de cada palavra código
print("Mensagem (4 bits) -> Palavra código (8 bits) -> Peso")
for m in all_messages:
    codeword = encode_message(m, G_extended)
    weight = np.sum(codeword)  # Calcula o peso (número de bits 1)
    codewords.append(codeword)
    weights.append(weight)
    print(f"{m} -> {codeword} -> {weight}")


Mensagem (4 bits) -> Palavra código (8 bits) -> Peso
(0, 0, 0, 0) -> [0 0 0 0 0 0 0 0] -> 0
(0, 0, 0, 1) -> [0 0 0 1 1 1 1 0] -> 4
(0, 0, 1, 0) -> [0 0 1 0 0 1 1 1] -> 4
(0, 0, 1, 1) -> [0 0 1 1 1 0 0 1] -> 4
(0, 1, 0, 0) -> [0 1 0 0 1 0 1 1] -> 4
(0, 1, 0, 1) -> [0 1 0 1 0 1 0 1] -> 4
(0, 1, 1, 0) -> [0 1 1 0 1 1 0 0] -> 4
(0, 1, 1, 1) -> [0 1 1 1 0 0 1 0] -> 4
(1, 0, 0, 0) -> [1 0 0 0 1 1 0 1] -> 4
(1, 0, 0, 1) -> [1 0 0 1 0 0 1 1] -> 4
(1, 0, 1, 0) -> [1 0 1 0 1 0 1 0] -> 4
(1, 0, 1, 1) -> [1 0 1 1 0 1 0 0] -> 4
(1, 1, 0, 0) -> [1 1 0 0 0 1 1 0] -> 4
(1, 1, 0, 1) -> [1 1 0 1 1 0 0 0] -> 4
(1, 1, 1, 0) -> [1 1 1 0 0 0 0 1] -> 4
(1, 1, 1, 1) -> [1 1 1 1 1 1 1 1] -> 8


In [6]:
# Calcula a distância mínima
def hamming_distance(codeword1, codeword2):
    return np.sum(codeword1 != codeword2)

min_distance = float('inf')

for i in range(len(codewords)):
    for j in range(i + 1, len(codewords)):
        dist = hamming_distance(codewords[i], codewords[j])
        if dist < min_distance:
            min_distance = dist

print("\nDistância mínima entre as palavras-código:", min_distance)

# Distribuição de pesos
weight_distribution = {i: weights.count(i) for i in range(9)}  # Peso varia de 0 a 8

print("Distribuição de pesos:")
for weight, count in weight_distribution.items():
    if count > 0:
        print(f"Peso {weight}: {count} palavra(s) código")


Distância mínima entre as palavras-código: 4
Distribuição de pesos:
Peso 0: 1 palavra(s) código
Peso 4: 14 palavra(s) código
Peso 8: 1 palavra(s) código


In [7]:
# Matriz (8,4) geradora do código de Hamming
G_input = np.array([
              [1, 0, 0, 0, 1, 1, 0, 1],  
              [0, 1, 0, 0, 1, 0, 1, 1],  
              [0, 0, 1, 0, 0, 1, 1, 1],  
              [0, 0, 0, 1, 1, 1, 1, 0]]) 


In [8]:
# Inicializando matriz de padrões de erro com 16 linhas
errorMatrix = np.zeros((16, 2**k, n), dtype=int)

# Gerando palavras código aleatórias para cada coluna da primeira linha (exceto na primeira posição)
for col in range(1, 2**k):
    errorMatrix[0, col] = np.random.randint(2, size=n) 

# Preenchendo a primeira coluna com a matriz identidade para padrões de erro de 1 bit
for i in range(1, min(9, 16)):
    errorMatrix[i, 0] = np.eye(n, dtype=int)[i-1]

# Gerando padrões de erro para 1 bit
for row in range(1, 9):  # Para as linhas 1 a 8
    for col in range(1, 2**k):  # Para todas as colunas
        errorMatrix[row, col] = (errorMatrix[0, col] + errorMatrix[row, 0]) % 2

# Gerando padrões de erro para 2 bits
two_bit_errors = list(it.combinations(range(n), 2))

# Contador para controlar o número de padrões de dois bits
two_bit_count = 0  

# Laço para terminar com as linhas da tabela (16 linhas no total)
for pos in two_bit_errors:
    if 9 + two_bit_count >= 16: 
        break

    error_pattern = np.zeros(n, dtype=int)
    error_pattern[list(pos)] = 1
    errorMatrix[9 + two_bit_count, 0] = error_pattern

    # Aplicando a combinação de dois bits de erro na matriz
    for col in range(1, 2**k):
        errorMatrix[9 + two_bit_count, col] = (errorMatrix[0, col] + errorMatrix[9 + two_bit_count, 0]) % 2
    
    two_bit_count += 1  # Incrementa o contador de padrões de dois bits

# Preencher as linhas restantes com padrões aleatórios, se necessário
for i in range(9 + two_bit_count, 16):
    for col in range(2**k):
        errorMatrix[i, col] = np.random.randint(2, size=n)  # Gera 0s e 1s aleatórios

# Inicializando a matriz de pesos
w_matrix = np.zeros((16, 2**k), dtype=int)

# Calculando os pesos para cada padrão de erro
for row in range(16):
    for col in range(2**k):
        w_matrix[row, col] = sum(errorMatrix[row, col])

# Impressão da matriz de padrões de erro
print("Matriz de Padrões de Erro (ap):")
for i in range(errorMatrix.shape[0]):
    for j in range(errorMatrix.shape[1]):
        print(f"{''.join(map(str, errorMatrix[i, j]))}", end=" ")
    print()

Matriz de Padrões de Erro (ap):
00000000 11011001 01011101 11110101 00110011 00011101 11010100 11111110 01111010 01101010 00100010 10000000 00000110 00011110 00010101 10110100 
10000000 01011001 11011101 01110101 10110011 10011101 01010100 01111110 11111010 11101010 10100010 00000000 10000110 10011110 10010101 00110100 
01000000 10011001 00011101 10110101 01110011 01011101 10010100 10111110 00111010 00101010 01100010 11000000 01000110 01011110 01010101 11110100 
00100000 11111001 01111101 11010101 00010011 00111101 11110100 11011110 01011010 01001010 00000010 10100000 00100110 00111110 00110101 10010100 
00010000 11001001 01001101 11100101 00100011 00001101 11000100 11101110 01101010 01111010 00110010 10010000 00010110 00001110 00000101 10100100 
00001000 11010001 01010101 11111101 00111011 00010101 11011100 11110110 01110010 01100010 00101010 10001000 00001110 00010110 00011101 10111100 
00000100 11011101 01011001 11110001 00110111 00011001 11010000 11111010 01111110 01101110 00100110

In [9]:
# Calcular síndromes
H = np.array([[1, 1, 0, 1, 1, 0, 0, 0],
              [1, 0, 1, 1, 0, 1, 0, 0],
              [0, 1, 1, 1, 0, 0, 1, 0],
              [1, 1, 1, 0, 0, 0, 0, 1]])

syndrome = (H @ errorMatrix[:, 0, :].T) % 2

# Criação da para as síndromes e padrões de erro
e_s = pd.DataFrame(columns=["syndrome", "error"])
e_s["syndrome"] = ["".join(map(str, s)) for s in syndrome.T]
e_s["error"] = ["".join(map(str, err)) for err in errorMatrix[:, 0, :]]

# Filtrar apenas as entradas únicas
e_s = e_s.drop_duplicates()

# Exibir o DataFrame resultante
print(e_s)

   syndrome     error
0      0000  00000000
1      1101  10000000
2      1011  01000000
3      0111  00100000
4      1110  00010000
5      1000  00001000
6      0100  00000100
7      0010  00000010
8      0001  00000001
9      0110  11000000
10     1010  10100000
11     0011  10010000
12     0101  10001000
13     1001  10000100
14     1111  10000010
15     1100  10000001


In [10]:
# Verificação dos erros em cada bit
print("\nVerificação de Erros em Cada Bit:")
for index, row in e_s.iterrows():
    syndrome_value = row["syndrome"]
    error_value = row["error"]
    
    # Verificando onde os erros ocorrem
    error_bits = [i for i in range(len(error_value)) if error_value[i] == '1']
    
    if len(error_bits) > 0:  # Se houver um ou mais erros
        print(f"Síndrome: {syndrome_value}, Erros detectados nos bits: {', '.join(str(bit + 1) for bit in error_bits)}")


Verificação de Erros em Cada Bit:
Síndrome: 1101, Erros detectados nos bits: 1
Síndrome: 1011, Erros detectados nos bits: 2
Síndrome: 0111, Erros detectados nos bits: 3
Síndrome: 1110, Erros detectados nos bits: 4
Síndrome: 1000, Erros detectados nos bits: 5
Síndrome: 0100, Erros detectados nos bits: 6
Síndrome: 0010, Erros detectados nos bits: 7
Síndrome: 0001, Erros detectados nos bits: 8
Síndrome: 0110, Erros detectados nos bits: 1, 2
Síndrome: 1010, Erros detectados nos bits: 1, 3
Síndrome: 0011, Erros detectados nos bits: 1, 4
Síndrome: 0101, Erros detectados nos bits: 1, 5
Síndrome: 1001, Erros detectados nos bits: 1, 6
Síndrome: 1111, Erros detectados nos bits: 1, 7
Síndrome: 1100, Erros detectados nos bits: 1, 8
