In [49]:
# Import das bibliotecas do Python
import sys
import komm
import numpy as np
import pandas as pd
import itertools as it
from itertools import product
from fractions import Fraction 

# Cria um objeto do código de Hamming (7,4)
hamm74 = komm.HammingCode(3)
(n, k) = (hamm74.length, hamm74.dimension)

# Imprime o código de Hamming (7,4)
print("Código de Hamming (7,4):")
print(n, k)

# Cria e Imprime a matriz geradora G (7,4)
G = hamm74.generator_matrix
print("Matriz geradora G (7,4):")
print(G)

Código de Hamming (7,4):
7 4
Matriz geradora G (7,4):
[[1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 1 1]]


In [50]:
# Calcula o bit de paridade para cada linha e adiciona à matriz

# Calcula a paridade (soma módulo 2 de cada linha)
parity_column = np.sum(G, axis=1)


# Adiciona a coluna de paridade
G_extended = np.hstack((G, parity_column.reshape(-1, 1)))  

# Imprime a matriz geradora estendida (8,4)
print("\nMatriz geradora estendida G (8,4):")
print(G_extended)

# Calcula o número de bits de mensagem
print("Número de bits de mensagem:", m)


Matriz geradora estendida G (8,4):
[[1 0 0 0 1 1 0 3]
 [0 1 0 0 1 0 1 3]
 [0 0 1 0 0 1 1 3]
 [0 0 0 1 1 1 1 4]]
Número de bits de mensagem: (1, 1, 1, 1)


In [51]:
# Define a função para mapear a mensagem para uma palavra código de 8 bits
def encode_message(m, G_extended):
    # Converte a mensagem em um array numpy, caso ainda não seja
    m = np.array(m)
    # Multiplica a mensagem pela matriz geradora estendida no campo GF(2)
    codeword = np.dot(m, G_extended) % 2  # Calcula a palavra código em aritmética módulo 2
    return codeword

# Exemplo de uso
message = [1, 0, 1, 1]  # Mensagem de 4 bits
codeword = encode_message(message, G_extended)

print("Mensagem de entrada (4 bits):", message)
print("Palavra código gerada (8 bits):", codeword)

# Altera o comprimento de n para 8
n = n + 1

# calcula o número de bits da mensagem 
m_lenght = n - k

Mensagem de entrada (4 bits): [1, 0, 1, 1]
Palavra código gerada (8 bits): [1 0 1 1 0 1 0 0]


In [52]:
# Gera todas as mensagens de 4 bits possíveis
all_messages = list(product([0, 1], repeat=4))  # Gera combinações de 4 bits

# Exibe cada mensagem e sua palavra código correspondente
print("Mensagem (4 bits) -> Palavra código (8 bits)")
for m in all_messages:
    codeword = encode_message(m, G_extended)
    print(f"{m} -> {codeword}")

Mensagem (4 bits) -> Palavra código (8 bits)
(0, 0, 0, 0) -> [0 0 0 0 0 0 0 0]
(0, 0, 0, 1) -> [0 0 0 1 1 1 1 0]
(0, 0, 1, 0) -> [0 0 1 0 0 1 1 1]
(0, 0, 1, 1) -> [0 0 1 1 1 0 0 1]
(0, 1, 0, 0) -> [0 1 0 0 1 0 1 1]
(0, 1, 0, 1) -> [0 1 0 1 0 1 0 1]
(0, 1, 1, 0) -> [0 1 1 0 1 1 0 0]
(0, 1, 1, 1) -> [0 1 1 1 0 0 1 0]
(1, 0, 0, 0) -> [1 0 0 0 1 1 0 1]
(1, 0, 0, 1) -> [1 0 0 1 0 0 1 1]
(1, 0, 1, 0) -> [1 0 1 0 1 0 1 0]
(1, 0, 1, 1) -> [1 0 1 1 0 1 0 0]
(1, 1, 0, 0) -> [1 1 0 0 0 1 1 0]
(1, 1, 0, 1) -> [1 1 0 1 1 0 0 0]
(1, 1, 1, 0) -> [1 1 1 0 0 0 0 1]
(1, 1, 1, 1) -> [1 1 1 1 1 1 1 1]


In [53]:
# Calcula o peso de Hamming de uma palavra código

# Vetores para armazenar as palavras-código e seus pesos
codewords = []
weights = []

# Calcula o peso de Hamming de cada palavra código
print("Mensagem (4 bits) -> Palavra código (8 bits) -> Peso")
for m in all_messages:
    codeword = encode_message(m, G_extended)
    weight = np.sum(codeword)  # Calcula o peso (número de bits 1)
    codewords.append(codeword)
    weights.append(weight)
    print(f"{m} -> {codeword} -> {weight}")


Mensagem (4 bits) -> Palavra código (8 bits) -> Peso
(0, 0, 0, 0) -> [0 0 0 0 0 0 0 0] -> 0
(0, 0, 0, 1) -> [0 0 0 1 1 1 1 0] -> 4
(0, 0, 1, 0) -> [0 0 1 0 0 1 1 1] -> 4
(0, 0, 1, 1) -> [0 0 1 1 1 0 0 1] -> 4
(0, 1, 0, 0) -> [0 1 0 0 1 0 1 1] -> 4
(0, 1, 0, 1) -> [0 1 0 1 0 1 0 1] -> 4
(0, 1, 1, 0) -> [0 1 1 0 1 1 0 0] -> 4
(0, 1, 1, 1) -> [0 1 1 1 0 0 1 0] -> 4
(1, 0, 0, 0) -> [1 0 0 0 1 1 0 1] -> 4
(1, 0, 0, 1) -> [1 0 0 1 0 0 1 1] -> 4
(1, 0, 1, 0) -> [1 0 1 0 1 0 1 0] -> 4
(1, 0, 1, 1) -> [1 0 1 1 0 1 0 0] -> 4
(1, 1, 0, 0) -> [1 1 0 0 0 1 1 0] -> 4
(1, 1, 0, 1) -> [1 1 0 1 1 0 0 0] -> 4
(1, 1, 1, 0) -> [1 1 1 0 0 0 0 1] -> 4
(1, 1, 1, 1) -> [1 1 1 1 1 1 1 1] -> 8


In [54]:
# Calcula a distância mínima
def hamming_distance(codeword1, codeword2):
    return np.sum(codeword1 != codeword2)

min_distance = float('inf')

for i in range(len(codewords)):
    for j in range(i + 1, len(codewords)):
        dist = hamming_distance(codewords[i], codewords[j])
        if dist < min_distance:
            min_distance = dist

print("\nDistância mínima entre as palavras-código:", min_distance)

# Distribuição de pesos
weight_distribution = {i: weights.count(i) for i in range(9)}  # Peso varia de 0 a 8

print("Distribuição de pesos:")
for weight, count in weight_distribution.items():
    if count > 0:
        print(f"Peso {weight}: {count} palavra(s) código")


Distância mínima entre as palavras-código: 4
Distribuição de pesos:
Peso 0: 1 palavra(s) código
Peso 4: 14 palavra(s) código
Peso 8: 1 palavra(s) código


In [55]:
# Matriz (8,4) geradora do código de Hamming
G_input = np.array([
              [1, 0, 0, 0, 1, 1, 0, 1],  
              [0, 1, 0, 0, 1, 0, 1, 1],  
              [0, 0, 1, 0, 0, 1, 1, 1],  
              [0, 0, 0, 1, 1, 1, 1, 0]]) 

In [56]:
# Inicializando matriz de padrões de erro
errorMatrix = np.zeros((2**m_lenght, 2**k, n), dtype=int)

# Gerando palavras código aleatórias para cada coluna da primeira linha
for col in range(2**k):
    errorMatrix[0, col] = np.random.randint(2, size=n)  # Gera 0s e 1s aleatórios para cada coluna

# Inicializando a primeira linha com os dados de paridade
errorMatrix[1:9, 0] = np.eye(n)[:8]  # Preenchendo as primeiras 8 linhas da coluna 0 com a matriz identidade

# Gerar padrões de erro para 1 e 2 bits de erro
for row in range(1, 9):
    for col in range(1, 2**k):
        errorMatrix[row, col] = (errorMatrix[0, col] + errorMatrix[row, 0]) % 2

# Criando padrões de erro para 1 e 2 bits
error1 = []
error2 = []

# Calculando padrões de erro para um bit de erro em cada posição
for pos in range(n):
    error_pattern = np.zeros(n, dtype=int)
    error_pattern[pos] = 1
    error1.append(error_pattern)

# Calculando padrões de erro para dois bits de erro em cada posição
positions = it.combinations(range(n), 2)
for pos in positions:
    error_pattern = np.zeros(n, dtype=int)
    error_pattern[list(pos)] = 1
    error2.append(error_pattern)

# Preenchendo a matriz de padrões de erro com padrões de erro de 1 bit
line_index = 0
for pattern in error1:
    if line_index < 2**m_lenght:
        errorMatrix[line_index, 0] = pattern
        line_index += 1

# Preenchendo a matriz de padrões de erro com padrões de erro de 2 bits
for pattern in error2:
    if line_index < 2**m_lenght:
        errorMatrix[line_index, 0] = pattern
        line_index += 1

# Inicializando a matriz de pesos
w_matrix = np.zeros((2**m_lenght, 2**k), dtype=int)

# Calculando os pesos para cada padrão de erro
for row in range(0, 2**m_lenght):
    for col in range(0, 2**k):
        w_matrix[row, col] = sum(errorMatrix[row, col])

# Impressão da matriz de padrões de erro
print("Matriz de Padrões de Erro (errorMatrix):")
for i in range(errorMatrix.shape[0]):
    for j in range(errorMatrix.shape[1]):
        print(f"{''.join(map(str, errorMatrix[i, j]))}", end=" ")
    print()

Matriz de Padrões de Erro (errorMatrix):
10000000 01110010 01101001 11111000 00111000 10001010 10000011 00100101 10001110 11101010 10110110 01011010 11011100 10000011 11101101 10111110 
01000000 11110010 11101001 01111000 10111000 00001010 00000011 10100101 00001110 01101010 00110110 11011010 01011100 00000011 01101101 00111110 
00100000 00110010 00101001 10111000 01111000 11001010 11000011 01100101 11001110 10101010 11110110 00011010 10011100 11000011 10101101 11111110 
00010000 01010010 01001001 11011000 00011000 10101010 10100011 00000101 10101110 11001010 10010110 01111010 11111100 10100011 11001101 10011110 
00001000 01100010 01111001 11101000 00101000 10011010 10010011 00110101 10011110 11111010 10100110 01001010 11001100 10010011 11111101 10101110 
00000100 01111010 01100001 11110000 00110000 10000010 10001011 00101101 10000110 11100010 10111110 01010010 11010100 10001011 11100101 10110110 
00000010 01110110 01101101 11111100 00111100 10001110 10000111 00100001 10001010 11101110

In [57]:
# Calcular síndromes
H = np.array([[1, 1, 0, 1, 1, 0, 0, 0],
              [1, 0, 1, 1, 0, 1, 0, 0],
              [0, 1, 1, 1, 0, 0, 1, 0],
              [1, 1, 1, 0, 0, 0, 0, 1]])

syndrome = (H @ errorMatrix[:, 0, :].T) % 2

# Criação da para as síndromes e padrões de erro
e_s = pd.DataFrame(columns=["syndrome", "error"])
e_s["syndrome"] = ["".join(map(str, s)) for s in syndrome.T]
e_s["error"] = ["".join(map(str, err)) for err in errorMatrix[:, 0, :]]

# Filtrar apenas as entradas únicas
e_s = e_s.drop_duplicates()

# Exibir o DataFrame resultante
print(e_s)

   syndrome     error
0      1101  10000000
1      1011  01000000
2      0111  00100000
3      1110  00010000
4      1000  00001000
5      0100  00000100
6      0010  00000010
7      0001  00000001
8      0110  11000000
9      1010  10100000
10     0011  10010000
11     0101  10001000
12     1001  10000100
13     1111  10000010
14     1100  10000001
15     1100  01100000


In [58]:
# Verificação dos erros em cada bit
print("\nVerificação de Erros em Cada Bit:")
for index, row in e_s.iterrows():
    syndrome_value = row["syndrome"]
    error_value = row["error"]
    
    # Verificando onde os erros ocorrem
    error_bits = [i for i in range(len(error_value)) if error_value[i] == '1']
    
    if len(error_bits) > 0:  # Se houver um ou mais erros
        print(f"Síndrome: {syndrome_value}, Erros detectados nos bits: {', '.join(str(bit + 1) for bit in error_bits)}")


Verificação de Erros em Cada Bit:
Síndrome: 1101, Erros detectados nos bits: 1
Síndrome: 1011, Erros detectados nos bits: 2
Síndrome: 0111, Erros detectados nos bits: 3
Síndrome: 1110, Erros detectados nos bits: 4
Síndrome: 1000, Erros detectados nos bits: 5
Síndrome: 0100, Erros detectados nos bits: 6
Síndrome: 0010, Erros detectados nos bits: 7
Síndrome: 0001, Erros detectados nos bits: 8
Síndrome: 0110, Erros detectados nos bits: 1, 2
Síndrome: 1010, Erros detectados nos bits: 1, 3
Síndrome: 0011, Erros detectados nos bits: 1, 4
Síndrome: 0101, Erros detectados nos bits: 1, 5
Síndrome: 1001, Erros detectados nos bits: 1, 6
Síndrome: 1111, Erros detectados nos bits: 1, 7
Síndrome: 1100, Erros detectados nos bits: 1, 8
Síndrome: 1100, Erros detectados nos bits: 2, 3
