In [1]:
import komm

In [2]:
code1 = komm.FixedToVariableCode.from_codewords(4, [(0,0), (0,1), (1,0), (1,1)])
code2 = komm.FixedToVariableCode.from_codewords(4, [(1,), (0,1), (0,0,0), (0,0,1)])
code3 = komm.FixedToVariableCode.from_codewords(4, [(0,), (0,1), (0,1,1), (0,1,1,1)])
code4 = komm.FixedToVariableCode.from_codewords(4, [(0,), (1,), (0,0), (1,1)])

In [3]:
print(code1.is_uniquely_decodable(), code1.is_prefix_free())
print(code2.is_uniquely_decodable(), code2.is_prefix_free())
print(code3.is_uniquely_decodable(), code3.is_prefix_free())
print(code4.is_uniquely_decodable(), code4.is_prefix_free())

True True
True True
True False
False False


In [4]:
palavra = [1, 0, 1, 0, 2, 0]

bits = code1.encode(palavra)
print(bits)
palavra_hat = code1.decode(bits)
print(palavra_hat)

bits = code2.encode(palavra)
print(bits)
palavra_hat = code2.decode(bits)
print(palavra_hat)

bits = code3.encode(palavra)
print(bits)

#bits = code4.encode(palavra)
#print(bits)

[0 1 0 0 0 1 0 0 1 0 0 0]
[1 0 1 0 2 0]
[0 1 1 0 1 1 0 0 0 1]
[1 0 1 0 2 0]
[0 1 0 0 1 0 0 1 1 0]


In [5]:
pmf = [1/2, 1/4, 1/8, 1/8]
print(code1.rate(pmf))
print(code2.rate(pmf))
print(code3.rate(pmf))
print(code4.rate(pmf))

2.0
1.75
1.875
1.25


In [6]:
dms = komm.DiscreteMemorylessSource(pmf)
texto = dms(10000)
bits1 = code1.encode(texto)
print(len(bits1))
bits2 = code2.encode(texto)
print(len(bits2))
bits3 = code3.encode(texto)
print(len(bits3))

dms.entropy()

20000
17512
18766


np.float64(1.75)

In [7]:
# Huffman

pmf1 = [1/2, 1/4, 1/8, 1/8]
huff1 = komm.HuffmanCode(pmf1)
print(huff1.codewords)

pmf2 = [0.4, 0.2, 0.2, 0.1, 0.1]
huff2 = komm.HuffmanCode(pmf2)
print(huff2.codewords, huff2.rate(pmf2))

huff2a = komm.HuffmanCode(pmf2, policy="low")
print(huff2a.codewords, huff2a.rate(pmf2))

[(1,), (0, 1), (0, 0, 1), (0, 0, 0)]
[(0, 0), (1, 1), (1, 0), (0, 1, 1), (0, 1, 0)] 2.2
[(1,), (0, 1), (0, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1)] 2.2
