Teste Aula 1 - COM 2

In [1]:
import numpy as np
import komm

# Código de Repetição

In [2]:
rep31 = komm.RepetitionCode(3)
(n, k) = (rep31.length, rep31.dimension)
# rep31.enc_mapping([1])
print(n,k)
rep31.generator_matrix


3 1


array([[1, 1, 1]])

# Código de Paridade simples

In [3]:
spc32 = komm.SingleParityCheckCode(3)
(n, k) = (spc32.length, spc32.dimension)
# rep31.enc_mapping([1])
print(n,k)
spc32.generator_matrix



3 2


array([[1, 0, 1],
       [0, 1, 1]])

# Distância de Hamming

In [14]:
hamm74 = komm.HammingCode(3)
(n, k) = (hamm74.length, hamm74.dimension)
G = hamm74.generator_matrix
print(n,k)
print("Matriz Geradora: \n\n", G ,"\n")

u = np.array([1,0,1,1])
print("Palavra de Informação: " , u)

v = (u @ G) % 2 

print("Palavra Código: " , v)

7 4
Matriz Geradora: 

 [[1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 1 1]] 

Palavra de Informação:  [1 0 1 1]
Palavra Código:  [1 0 1 1 0 1 0]


In [ ]:
# V é palavra código se e somente se V * H^T = 0